# Generated by Django 5.2.1 on 2026-03-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razao social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('state_registration', models.CharField(blank=True, max_length=30, verbose_name='inscricao estadual')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('trade_name', 'legal_name'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='inicio')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ('-is_active', '-starts_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EventCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'verbose_name': 'empresa do evento',
                'verbose_name_plural': 'empresas do evento',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='events', through='core.EventCompany', to='core.company'),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'verbose_name': 'participante do evento',
                'verbose_name_plural': 'participantes do evento',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('is_representative', models.BooleanField(default=False, verbose_name='representante')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='comissao (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ManyToManyField(blank=True, related_name='participants', through='core.EventParticipant', to='core.event')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant'),
        ),
        migrations.CreateModel(
            name='ParticipantCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
            ],
            options={
                'verbose_name': 'empresa do participante',
                'verbose_name_plural': 'empresas dos participantes',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='participants', through='core.ParticipantCompany', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='eventcompany',
            constraint=models.UniqueConstraint(fields=('event', 'company'), name='unique_event_company'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='unique_event_participant'),
        ),
        migrations.AddConstraint(
            model_name='participantcompany',
            constraint=models.UniqueConstraint(fields=('participant', 'company'), name='unique_participant_company'),
        ),
    ]
