# Generated by Django 5.2.1 on 2026-03-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.RemoveConstraint(
            model_name='eventcompany',
            name='unique_event_company',
        ),
        migrations.RemoveConstraint(
            model_name='eventparticipant',
            name='unique_event_participant',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='participant',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('trade_name', 'legal_name'), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='participantcompany',
            options={'verbose_name': 'vinculo cliente-participante', 'verbose_name_plural': 'vinculos cliente-participante'},
        ),
    ]
