# Generated by Django 5.2.1 on 2026-03-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_companies_remove_participant_events_and_more'),
        ('sales', '0002_remove_category_unique_category_per_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCompany',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
