# Generated by Django 5.2.1 on 2026-03-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_event_delete_eventcompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='contato')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ('trade_name',),
            },
        ),
    ]
