# Generated by Django 5.2.1 on 2026-03-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='nome do perfil')),
                ('parser_key', models.CharField(blank=True, max_length=60, verbose_name='layout')),
                ('supplier_hint_pattern', models.CharField(blank=True, max_length=255, verbose_name='nome lido no arquivo')),
                ('file_name_tokens', models.CharField(blank=True, max_length=255, verbose_name='palavras do nome do arquivo')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observacoes')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='usos')),
                ('last_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_profiles', to='core.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'perfil de importacao do fornecedor',
                'verbose_name_plural': 'perfis de importacao do fornecedor',
                'ordering': ('supplier__trade_name', 'name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('supplier', 'parser_key', 'supplier_hint_pattern', 'file_name_tokens'), name='unique_supplier_import_profile_signature')],
            },
        ),
    ]
