# Generated by Django 5.2.1 on 2026-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebpicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=80, unique=True, verbose_name='nome')),
                ('api_company', models.CharField(blank=True, max_length=80, verbose_name='empresa API')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='token de integracao')),
                ('price_table_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da tabela de preco')),
                ('employee_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do funcionario')),
                ('representative_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do representante')),
                ('client_group_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do grupo de clientes')),
                ('current_account_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da conta corrente')),
                ('access_token', models.TextField(blank=True, verbose_name='access token')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao Webpic',
                'verbose_name_plural': 'configuracoes Webpic',
                'ordering': ('name',),
            },
        ),
    ]
