# Generated by Django 5.2.1 on 2026-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpicconfiguration',
            name='import_products_without_price',
            field=models.BooleanField(default=False, verbose_name='importar produtos sem preco'),
        ),
    ]
