# Generated by Django 5.2.1 on 2026-03-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_companies_remove_participant_events_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='color',
            name='unique_color_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_reference_by_company_event',
        ),
        migrations.RemoveConstraint(
            model_name='size',
            name='unique_size_per_company',
        ),
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
        migrations.RemoveField(
            model_name='color',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='event',
        ),
        migrations.RemoveField(
            model_name='size',
            name='company',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.company', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=20, unique=True, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
