# Generated by Django 5.2.1 on 2026-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_category_unique_category_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='webpic_exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exportado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='webpic_integrated',
            field=models.BooleanField(default=False, verbose_name='integrado na Webpic'),
        ),
        migrations.AddField(
            model_name='order',
            name='webpic_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='payload Webpic'),
        ),
        migrations.AddField(
            model_name='order',
            name='webpic_response',
            field=models.JSONField(blank=True, null=True, verbose_name='resposta Webpic'),
        ),
    ]
