# Generated by Django 5.2.1 on 2026-03-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_webpic_exported_at_order_webpic_integrated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_target',
        ),
    ]
