# Generated by Django 5.2.1 on 2026-03-26 01:45

from django.db import migrations, models


def consolidate_variants_by_color(apps, schema_editor):
    ProductVariant = apps.get_model("sales", "ProductVariant")
    OrderItem = apps.get_model("sales", "OrderItem")
    db_alias = schema_editor.connection.alias

    grouped_variants = {}
    for variant in ProductVariant.objects.using(db_alias).order_by("product_id", "color_id", "pk"):
        grouped_variants.setdefault((variant.product_id, variant.color_id), []).append(variant)

    for variants in grouped_variants.values():
        if len(variants) <= 1:
            continue

        primary = next(
            (variant for variant in variants if (variant.barcode or "").strip()),
            variants[0],
        )
        duplicate_ids = [variant.pk for variant in variants if variant.pk != primary.pk]

        if not (primary.barcode or "").strip():
            for variant in variants:
                barcode = (variant.barcode or "").strip()
                if barcode:
                    primary.barcode = barcode
                    primary.save(update_fields=["barcode"])
                    break

        if any(variant.is_active for variant in variants) and not primary.is_active:
            primary.is_active = True
            primary.save(update_fields=["is_active"])

        if duplicate_ids:
            OrderItem.objects.using(db_alias).filter(variant_id__in=duplicate_ids).update(variant_id=primary.pk)
            ProductVariant.objects.using(db_alias).filter(pk__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_product_sales_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("MT", "Metro"), ("KG", "Peso (kg)")],
                default="MT",
                max_length=2,
                verbose_name="unidade",
            ),
        ),
        migrations.RunPython(consolidate_variants_by_color, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="unique_variant_by_matrix",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="size",
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ("product__reference", "color__name"),
                "verbose_name": "variante do produto",
                "verbose_name_plural": "variantes do produto",
            },
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "color"),
                name="unique_variant_by_color",
            ),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
