# Generated by Django 5.2.1 on 2026-03-26 01:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplier'),
        ('sales', '0005_remove_product_sizes_remove_productvariant_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de entrada')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='core.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'entrada de estoque',
                'verbose_name_plural': 'entradas de estoque',
                'ordering': ('-received_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=24, unique=True, verbose_name='codigo do rolo')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade inicial')),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='saldo disponivel')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='sales.productvariant', verbose_name='variante')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='sales.stockentry', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'rolo de tecido',
                'verbose_name_plural': 'rolos de tecido',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
