# Generated by Django 5.2.1 on 2026-03-26 02:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_stockentry_fabricroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sales.fabricroll', verbose_name='rolo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0, verbose_name='itens'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade'),
        ),
    ]
