# Generated by Django 5.2.1 on 2026-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_orderitem_roll_alter_order_total_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('reserved', 'Reservado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=16, verbose_name='status'),
        ),
    ]
