# Generated by Django 5.2.1 on 2026-03-27 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def populate_stock_movements(apps, schema_editor):
    FabricRoll = apps.get_model("sales", "FabricRoll")
    OrderItem = apps.get_model("sales", "OrderItem")
    StockMovement = apps.get_model("sales", "StockMovement")

    movements_to_create = []
    for roll in FabricRoll.objects.all().order_by("pk"):
        balance = (roll.initial_quantity or Decimal("0.000")).quantize(Decimal("0.001"))
        movements_to_create.append(
            StockMovement(
                roll_id=roll.pk,
                movement_type="entry",
                quantity=balance,
                balance_after=balance,
                stock_entry_id=roll.stock_entry_id,
                is_system_generated=True,
                effective_at=roll.created_at,
            )
        )

        order_items = OrderItem.objects.filter(
            roll_id=roll.pk,
            order__status__in=["reserved", "confirmed"],
        ).select_related("order").order_by("order__created_at", "created_at", "pk")

        for item in order_items:
            quantity = (item.quantity or Decimal("0.000")).quantize(Decimal("0.001"))
            balance = (balance - quantity).quantize(Decimal("0.001"))
            if balance < 0:
                balance = Decimal("0.000")
            movements_to_create.append(
                StockMovement(
                    roll_id=roll.pk,
                    movement_type="confirmed" if item.order.status == "confirmed" else "reserved",
                    quantity=quantity,
                    balance_after=balance,
                    order_id=item.order_id,
                    order_item_id=item.pk,
                    is_system_generated=True,
                    effective_at=item.order.updated_at,
                )
            )

    if movements_to_create:
        StockMovement.objects.bulk_create(movements_to_create, batch_size=500)


def clear_stock_movements(apps, schema_editor):
    StockMovement = apps.get_model("sales", "StockMovement")
    StockMovement.objects.filter(is_system_generated=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('reserved', 'Reserva'), ('confirmed', 'Confirmacao')], max_length=16, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='saldo apos movimentacao')),
                ('is_system_generated', models.BooleanField(default=True, verbose_name='gerado pelo sistema')),
                ('effective_at', models.DateTimeField(verbose_name='data da movimentacao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.order', verbose_name='pedido')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.orderitem', verbose_name='item do pedido')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sales.fabricroll', verbose_name='rolo')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.stockentry', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'movimentacao de estoque',
                'verbose_name_plural': 'movimentacoes de estoque',
                'ordering': ('-effective_at', '-pk'),
            },
        ),
        migrations.RunPython(populate_stock_movements, clear_stock_movements),
    ]
