# Generated by Django 5.2.1 on 2026-03-27 01:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('adjustment_in', 'Ajuste de entrada'), ('adjustment_out', 'Ajuste de saida'), ('return', 'Devolucao'), ('reserved', 'Reserva'), ('confirmed', 'Confirmacao')], max_length=16, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('adjustment_in', 'Ajuste de entrada'), ('adjustment_out', 'Ajuste de saida'), ('return', 'Devolucao')], max_length=16, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='sales.fabricroll', verbose_name='rolo')),
            ],
            options={
                'verbose_name': 'ajuste de estoque',
                'verbose_name_plural': 'ajustes de estoque',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.stockadjustment', verbose_name='ajuste'),
        ),
    ]
